version: '3'
services:
  serviceregistry: 
    image: 'bryanyidev/serviceregistry:latest'
    container_name: serviceregistry
    ports:
      - '8761:8761'
  configserver: 
    image: 'bryanyidev/configserver:latest'
    container_name: configserver
    ports:
      - '9296:9296'
    depends_on: 
      - serviceregistry
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://configserver:9296/actuator/health"]
      interval: 10s 
      timeout: 5s
      retries: 5
  cloudgateway: 
    image: 'bryanyidev/cloudgateway:latest'
    container_name: cloudgateway
    ports:
      - '9090:9090'
    depends_on: 
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
  productservice: 
    image: 'bryanyidev/productservice:latest'
    container_name: productservice
    ports:
      - '8080:8080'
    depends_on: 
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
      - DB_HOST=host.docker.internal
  paymentservice: 
    image: 'bryanyidev/paymentservice:latest'
    container_name: paymentservice
    ports:
      - '8082:8082'
    depends_on: 
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
      - DB_HOST=host.docker.internal
  orderservice: 
    image: 'bryanyidev/orderservice:latest'
    container_name: orderservice
    ports:
      - '8081:8081'
    depends_on: 
      configserver:
        condition: service_healthy
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
      - DB_HOST=host.docker.internal
