server:
  port: 8082

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    username: bryanyi
    password: stringsandtonesadmin
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/stringsandtones_paymentdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  config:
    import: configserver:${CONFIG_SERVER_URL:localhost:9296}
  zipkin:
    base-url: http://localhost:9411