server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    username: bryanyi
    password: stringsandtonesadmin
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/stringsandtones_ordersdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  config:
    import: configserver:http://localhost:9296
  zipkin:
    base-url: http://localhost:9411

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
